### ISSUE TITLE
Verify responses

### ISSUE THREAD

**Issue by chrislawlor** [pymetrics/pact-testgen#1]
Given a response (type?), figure out how to use pactman code to  verify it.

Should raise some exception if verification fails.

**Comment by lgoodridge** [comment]
Pactman verify source code: https://github.com/reecetech/pactman/blob/master/pactman/verifier/verify.py#L243

**Comment by chrislawlor** [comment]
```
class ResponseVerifier:
    interaction_name = "Response"

    def __init__(self, pact, interaction, result):
        self.pact = pact
        self.status = interaction.get("status", MISSING)
        self.headers = interaction.get("headers", MISSING)
        self.body = interaction.get("body", MISSING)
        rules = interaction.get("matchingRules", {})
        if pact.semver.major < 2:
            # there are no matchingRules in v1
            self.matching_rules = {}
        elif pact.semver.major < 3:
            self.matching_rules = rule_matchers_v2(rules)
        else:
            self.matching_rules = rule_matchers_v3(rules)
        self.result = result

    def verify(self, response):
```

* Initialize a `ResponseVerifier` with:
  * `pact`: 
  * `interaction`: dict-like, straight from the Pact file, has `status`, `headers`, `body`, and  `matchingRules` (all optional)
  * `result`: an instance of `pactman.verifier.Result`. I suspect we'll want our own subclass.
* Call `verifier.verify(response)`, where "response" seems to have the same API as a `requests.Response` - specifically `text`, `headers`, and `status_code`.

**Comment by chrislawlor** [comment]
In the generated test method:

`from pact_testgen import verify_response`

`verify_response(interaction, response)`

**Comment by lgoodridge** [comment]
https://github.com/pymetrics/pact-testgen/blob/master/pact_testgen/verify.py#L12

Will probably need some love eventually, but the method's there
