### ISSUE TITLE
What's in a name?

### ISSUE THREAD

**Issue by chrislawlor** [pymetrics/pact-testgen#16]
Need a name that doesn't imply that this project came from the folks over at pact.io.

Some ideas, or seeds for ideas:

* Something around contracts, or enforcing contracts. [synonyms for "contract"](https://www.thesaurus.com/browse/contract) may be useful.
* Contracts "bind" parties together - though "bind" has other meanings in CS, especially in the JS world.
* Ideally (maybe) have "py" in the name, "pact" itself is used from many languages, while this tool is python specific (at least while we're depending on pactman's verifier code).

**Comment by nashahzad** [comment]
> Need a name that doesn't imply that this project came from the folks over at pact.io.
> 
> Some ideas, or seeds for ideas:
> 
> * Something around contracts, or enforcing contracts. [synonyms for "contract"](https://www.thesaurus.com/browse/contract) may be useful.
> * Contracts "bind" parties together - though "bind" has other meanings in CS, especially in the JS world.
> * Ideally (maybe) have "py" in the name, "pact" itself is used from many languages, while this tool is python specific (at least while we're depending on pactman's verifier code).

some ideas off the top of my head:
* pymtracts (combine pymetrics + contracts)
* pym-tract-gen (combining pymetrics + contracts + generation and sounds like pym traction)

**Comment by mrenoch** [comment]
I like -tracts and tract-gen, though I did discover there already is a [pytracts](https://pypi.org/project/pytracts/) package.  

Do you think we need the `pym` brand in the title of this project.  It's not pymetrics specific, and it's origin will be clear when we publish. 

I am also thinking about a name that includes `enforcer` - `api-enforcer`?  `pynforcer`?

**Comment by nashahzad** [comment]
ahh, if it has nothing to do with pymetrics then yeah it'd make sense to not have the name be pymetrics esque. 

@mrenoch based off your ideas but just dropping one letter `pyforcer`?

**Comment by tommy-dorsey-pymetrics** [comment]
> I am also thinking about a name that includes `enforcer` - `api-enforcer`? `pynforcer`?

I'd suggest pact-escrow-pymetrics, or a variation thereof. 

[...]legal arrangement in which a third party temporarily holds [the deployment] until a particular condition has been met (e.g., the fulfillment of a [test case]).

We do want to avoid name confusion, but we also do want to be included for pact related keywords, right? On the js side, packages are org scoped, so there's clear delineation that @storybook/addon-docs is official, but storybook-addon-whatever is 3rd party by convention, and recommended by the maintainers. `eslint-config-airbnb` is another example from the js world where thing-othercompany is fairly standard, but I have no idea what the norms are for 🐍 .

 Does Pact (or PyPI) have a plugin ecosystem with a standard convention for this?

**Comment by chrislawlor** [comment]
@jessicagmarshall suggested `pympacts` over in slack

**Comment by chrislawlor** [comment]
@tommy-dorsey-pymetrics pypi (python package index, where python packages are published) has a flat namespace.

There's nothing inherently wrong with being `pact-something`, in fact for certain communities that's pretty common (e.g. there are many `django-*` packages that are not maintained by the Django Software Foundation).

Pymetrics is the copyright holder here, it's fine to have a pymetrics-flavored name.

Do keep in mind that this is a CLI tool, so a shorter name is preferable, though the entrypoint name doesn't have to be the same as the package name.

**Comment by chrislawlor** [comment]
I like `pyverify` but it's taken: https://pypi.org/project/pyverify/

**Comment by chrislawlor** [comment]
`pyforcer` is pretty cool!

**Comment by chrislawlor** [comment]
There is a `PyForce` package on PyPI:
```
Description:
    This is a module for bruteforcing district 833 school passwords using destiny quest.
```
🤔 😲

**Comment by chrislawlor** [comment]
I asked over in Pact's #general Slack channel about how they feel about third parties using "pact" in project names: https://pact-foundation.slack.com/archives/C5F4KFKR8/p1629400774287900

**Comment by chrislawlor** [comment]
Matt, one of the Pact cofounders, gave his blessing for using `pact` in our name 🎉
So, that option's open if we want to use it.

**Comment by chrislawlor** [comment]
In a rather tight poll, `pact-testgen` squeezed out the win by one vote. Thank you all for your excellent suggestions!
