### ISSUE TITLE
Write a template which takes a pact file representation -> test methods

### ISSUE THREAD

**Issue by chrislawlor** [pymetrics/pact-testgen#2]
[
  TestCase: setup, [test methods],
  TestCase: setup, [test methods]
]

Assume `self.client` exists

template context is a single class (however that's defined).

**Comment by david-a-jetter** [comment]
parameterize:
* import path
* test class baseclass name
* comment of pact file description

**Comment by lgoodridge** [comment]
https://github.com/pymetrics/pact-testgen/blob/master/pact_testgen/generators/django/generator.py
