### ISSUE TITLE
Convert to poetry

### ISSUE THREAD

**Issue by david-a-jetter** [pymetrics/pact-testgen#9]
Move setup.py and requirements files into poetry
Define a plugin for the entrypoint

**Comment by chrislawlor** [comment]
this is breaking tox at the moment (`make tests-all`) - tests pass, but dev deps are installed from `requirements_dev.txt`, and flake8 fails to run. I added a bunch of missing dev dependencies to pyproject.toml, but tox needs to be set up to use poetry instead of pip.

**Comment by chrislawlor** [comment]
Fixed tox flake8, was unrelated to Poetry. Still need to integrate Poetry + Tox. With this, and the entrypoint config, I think we can move fully over to Poetry. 

I'm still not entirely sold on losing editable installs, it's so much simpler do just do `pip install -e .` when working on a CLI tool, I can actually just call `pact-testgen` whenever I want, no "poetry run", no having to re-install it every time we change the code.

**Comment by lgoodridge** [comment]
Closed (for now) in favor of `pip install -e .`
